package-lock.json, package.json, release.config.js
testing branch protection rules
=> chore: remove semantic-release-git plugin

package-lock.json, package.json
=> chore(release): 1.6.4 [skip ci]

package-lock.json, package.json
=> chore(release): 1.6.6

script/cd, script/ci
- Check version numbers in `package.json` during CI to create a linear history.
- Organise CD script into functions to improve readability.
=> chore(ci/cd): improve CI/CD processes

package-lock.json, package.json
=> chore(release): 1.6.7

package-lock.json, package.json
=> chore(release): 1.6.8

script/ci
- get early feedback from changes
- anticipate npm lag
=> fix(ci): perform version check last

package-lock.json, package.json
=> chore(release): 1.6.9

.editorconfig
This PR tests the auto-merge functionality
=> refactor: make a comment change

package.json
**Do not merge**
This PR tests what the action does if the wrong change is made to the `package.json`
=> chore(release): Test wrong change

package.json
=> chore(release): Test auto merge 2.0

src/letters.ts
This PR adds a new letters array containing the letter `a` to test out the auto release functionality
=> feat: add letters

package-lock.json, package.json, src/letters.ts
=> fix: Add b

package-lock.json, package.json
Updating the version number in the repository following the release of v1.7.1
=> chore(release): 1.7.1

src/letters.ts
=> fix: add letter c

src/letters.ts
=> fix: add d

package-lock.json, package.json
Updating the version number in the repository following the release of v1.7.3
=> chore(release): 1.7.3

src/letters.ts
=> fix: add letter e

package-lock.json, package.json
Updating the version number in the repository following the release of v1.7.4
=> chore(release): 1.7.4

src/letters.ts
=> fix: Add f

package-lock.json, package.json
Updating the version number in the repository following the release of v1.7.5
=> chore(release): 1.7.5

src/letters.ts
=> fix: Add g

src/letters.ts
=> fix: add h

package-lock.json, package.json
Updating the version number in the repository following the release of v1.7.6
=> chore(release):1.7.6

package-lock.json, package.json, src/letters.ts
**DO NOT MERGE**
This PR is being used to test out the new `additional-changes` option
=> chore(release): add i

src/letters.ts
=> fix: add i

package.json
=> chore(release): 1.7.7

src/letters.ts
=> fix: add k

package.json
Updating the version number in the repository following the release of v1.7.9
=> chore(release): 1.7.9

src/letters.ts
=> feat: add l

package.json
Updating the version number in the repository following the release of v1.8.0
=> chore(release): 1.8.0

package.json, src/letters.ts
=> chore(release): change version and letters

src/letters.ts
=> fix: add m

package.json
Updating the version number in the repository following the release of v1.8.1
=> chore(release): 1.8.1

src/letters.ts
=> fix: add n

package.json
Updating the version number in the repository following the release of v1.8.2
=> chore(release): 1.8.2

package.json
Updating the version number in the repository following the release of v1.8.3
=> chore(release): 1.8.3

src/letters.ts
=> fix: add p

package.json
Updating the version number in the repository following the release of v1.8.4
=> chore(release): 1.8.4

src/letters.ts
=> fix: add q

package.json
Updating the version number in the repository following the release of v1.8.5
=> chore(release): 1.8.5

src/letters.ts
=> fix: add r

package.json
Updating the version number in the repository following the release of v1.8.6
=> chore(release): 1.8.6

src/letters.ts
=> feat: add s

package.json
Updating the version number in the repository following the release of v1.9.0
=> chore(release): 1.9.0

src/letters.ts
=> fix: add t

package.json
Updating the version number in the repository following the release of v1.9.1
=> chore(release): 1.9.1
